defmodule QuireWeb.WorkspaceLive.SignaturePlacementTest do
  use QuireWeb.ConnCase, async: false

  import Phoenix.LiveViewTest
  import Quire.AccountsFixtures, only: []

  alias Quire.Documents.{Document, Revision}
  alias Quire.Repo

  setup do
    user = user_fixture()
    doc = document_fixture(user)
    doc = revision_fixture(doc)
    %{user: user, doc: doc, conn: build_conn()}
  end

  describe "signature_use" do
    test "dispatches the saved signature to the client", %{user: user, doc: doc, conn: conn} do
      sig = %{
        "id" => Ecto.UUID.generate(),
        "label" => "My Sig",
        "type" => "draw",
        "data" => Jason.encode!(%{strokes: [], width: 200, height: 60}),
        "created_at" => DateTime.utc_now() |> DateTime.to_iso8601()
      }

      {:ok, _} =
        Quire.Accounts.update_user_settings(user.id, %{signatures: %{sig["id"] => sig}})

      {:ok, lv, _html} = live_workspace(doc, conn)

      lv
      |> element(~s{button[phx-click="toggle_panel"][phx-value-item="signatures"]})
      |> render_click()

      lv
      |> element(~s{button[phx-click="signature_use"][phx-value-id="#{sig["id"]}"]})
      |> render_click()

      assert_push_event(lv, "enable_signature_placement", %{signature: sent})
      assert sent["id"] == sig["id"]
      assert sent["type"] == "draw"
    end

    test "errors when the signature id is unknown", %{doc: doc, conn: conn} do
      {:ok, lv, _html} = live_workspace(doc, conn)

      lv
      |> element("#document-canvas")
      |> render_hook("signature_use", %{"id" => "missing"})

      assert has_element?(lv, ~s{[role="alert"]}, "Signature not found")
    end
  end

  describe "signature_placed" do
    test "embeds the signature, journals, and flushes a new revision", %{doc: doc, conn: conn} do
      {:ok, lv, _html} = live_workspace(doc, conn)
      png = File.read!(Path.expand("../../../fixtures/images/transparent.png", __DIR__))

      lv
      |> element("#document-canvas")
      |> render_hook("signature_placed", %{
        "page_index" => 0,
        "rect" => [72.0, 72.0, 200.0, 100.0],
        "png" => Base.encode64(png)
      })

      assert_push_event(lv, "open_document", %{url: url, password: nil})
      assert url == "/documents/#{doc.id}/pdf"

      # A new revision exists and its bytes render the placed signature
      updated = Repo.get!(Document, doc.id)
      assert updated.current_revision_id != doc.current_revision_id

      rev = Repo.get!(Revision, updated.current_revision_id)
      ref = Quire.Documents.Revision.storage_ref(rev)
      assert {:ok, bytes} = Quire.Storage.get(ref)

      assert {:ok, _} = Quire.Pdf.open(bytes)
      assert {:ok, render_ref} = Quire.Storage.put(bytes, name: "placed.pdf")
      assert {:ok, _png} = Quire.Render.Pdfium.render_page(render_ref, 0, dpi: 72)
    end

    test "rejects a bad rect", %{doc: doc, conn: conn} do
      {:ok, lv, _html} = live_workspace(doc, conn)
      png = File.read!(Path.expand("../../../fixtures/images/transparent.png", __DIR__))

      lv
      |> element("#document-canvas")
      |> render_hook("signature_placed", %{
        "page_index" => 0,
        "rect" => [10, 10, 5, 5],
        "png" => Base.encode64(png)
      })

      assert_push_event(lv, "signature_placement_failed", %{reason: reason})
      assert reason =~ "bad_rect"

      # No new revision was created
      updated = Repo.get!(Document, doc.id)
      assert updated.current_revision_id == doc.current_revision_id
    end
  end

  defp live_workspace(doc, conn) do
    {:ok, conn} = {:ok, log_in_user(conn, Quire.Repo.get!(Quire.Accounts.User, doc.user_id))}
    live(conn, ~p"/workspace/#{doc.id}")
  end

  defp user_fixture do
    %Quire.Accounts.User{
      id: Ecto.UUID.generate(),
      email: "user-#{System.unique_integer([:positive])}@example.com",
      hashed_password: "x"
    }
    |> Quire.Repo.insert!()
  end

  defp document_fixture(user) do
    %Document{
      id: Ecto.UUID.generate(),
      user_id: user.id,
      title: "sig-test.pdf"
    }
    |> Quire.Repo.insert!()
  end

  defp revision_fixture(doc) do
    # PDFium-generated bytes (lopdf-parseable — see signature_flatten_test)
    {:ok, ex_doc} =
      ExPdfium.open(File.read!(Path.expand("../../../fixtures/pdfs/simple_text.pdf", __DIR__)))

    {:ok, pdf} = ExPdfium.save_to_bytes(ex_doc)
    {:ok, ref} = Quire.Storage.put(pdf, name: "sig-test.pdf", content_type: "application/pdf")

    source = %{
      "storage_ref" => %{
        "adapter" => to_string(ref.adapter),
        "key" => ref.key,
        "name" => ref.name,
        "content_type" => ref.content_type,
        "byte_size" => ref.byte_size
      },
      "filename" => "sig-test.pdf"
    }

    {:ok, rev} = Quire.Documents.create_revision(doc, label: "v1", source: source)

    {:ok, updated} =
      doc
      |> Ecto.Changeset.change(%{current_revision_id: rev.id, page_count: 1})
      |> Quire.Repo.update()

    updated
  end
end
