defmodule Quire.Pades.CmsTest do
  use ExUnit.Case, async: true

  # The PAdES CMS tests exercise signed_data against a throwaway CA
  # certificate (test CA, pdf-4c6k). The fixture lives under /tmp and is
  # generated on demand so the test suite is self-contained on any machine
  # (in particular the pre-push hook). OpenSSL is a hard project dependency
  # (Brewfile), so shelling out is safe here.
  setup_all do
    unless File.exists?("/tmp/test_cert.der") and File.exists?("/tmp/test_key.pem") do
      System.cmd(
        "openssl",
        [
          "req",
          "-x509",
          "-newkey",
          "rsa:2048",
          "-keyout",
          "/tmp/test_key.pem",
          "-out",
          "/tmp/test_cert.pem",
          "-days",
          "365",
          "-nodes",
          "-subj",
          "/CN=Quire Test CA"
        ],
        stderr_to_stdout: true
      )

      System.cmd("openssl", [
        "x509",
        "-in",
        "/tmp/test_cert.pem",
        "-outform",
        "DER",
        "-out",
        "/tmp/test_cert.der"
      ])
    end

    :ok
  end

  setup do
    # Load test certificate and key generated by OpenSSL
    cert_der = File.read!("/tmp/test_cert.der")
    {:ok, pem_data} = File.read("/tmp/test_key.pem")
    [rsa_entry] = :public_key.pem_decode(pem_data)
    private_key = :public_key.pem_entry_decode(rsa_entry)

    %{cert_der: cert_der, private_key: private_key}
  end

  describe "build_signed_data/4" do
    test "builds valid CMS ContentInfo with SignedData", %{
      cert_der: cert_der,
      private_key: private_key
    } do
      content = "test data"
      content_hash = :crypto.hash(:sha256, content)
      signature = :public_key.sign(content_hash, :sha256, private_key)

      assert {:ok, cms_der} =
               Quire.Pades.Cms.build_signed_data(content_hash, signature, cert_der,
                 signature_algorithm: :rsa
               )

      # CMS should be reasonable size (under 2000 bytes for RSA 2048)
      assert byte_size(cms_der) < 2000

      # Outer structure: SEQUENCE
      {{0x30, outer_content}, rest} = Quire.Pades.Cms.decode_tlv(cms_der)
      assert rest == ""

      # Outer ContentInfo: SEQUENCE { contentType OID, content [0] EXPLICIT SignedData }
      {{0x06, oid_bytes}, rest2} = Quire.Pades.Cms.decode_tlv(outer_content)
      oid_tuple = decode_oid(oid_bytes)
      assert oid_tuple == {1, 2, 840, 113_549, 1, 7, 2}, "Expected signedData OID"

      # Next should be [0] EXPLICIT containing SignedData
      {{0xA0, signed_data_der}, rest3} = Quire.Pades.Cms.decode_tlv(rest2)
      assert rest3 == ""

      # SignedData: SEQUENCE
      {{0x30, _sd_content}, _} = Quire.Pades.Cms.decode_tlv(signed_data_der)
    end

    test "defaults to RSA signature algorithm", %{cert_der: cert_der, private_key: private_key} do
      content_hash = :crypto.hash(:sha256, "test")
      signature = :public_key.sign(content_hash, :sha256, private_key)

      assert {:ok, cms_der} =
               Quire.Pades.Cms.build_signed_data(content_hash, signature, cert_der)

      assert byte_size(cms_der) > 100
    end

    test "includes signer certificate in CMS", %{cert_der: cert_der, private_key: private_key} do
      content_hash = :crypto.hash(:sha256, "test")
      signature = :public_key.sign(content_hash, :sha256, private_key)

      assert {:ok, cms_der} =
               Quire.Pades.Cms.build_signed_data(content_hash, signature, cert_der)

      # The cert should appear somewhere in the CMS
      assert String.contains?(cms_der, cert_der)
    end

    test "contains SHA256 digest algorithm", %{cert_der: cert_der, private_key: private_key} do
      content_hash = :crypto.hash(:sha256, "test")
      signature = :public_key.sign(content_hash, :sha256, private_key)

      assert {:ok, cms_der} =
               Quire.Pades.Cms.build_signed_data(content_hash, signature, cert_der)

      # SHA256 OID: 2.16.840.1.101.3.4.2.1 → DER: 06 09 60 86 48 01 65 03 04 02 01
      sha256_oid_der = <<6, 9, 96, 134, 72, 1, 101, 3, 4, 2, 1>>
      assert String.contains?(cms_der, sha256_oid_der)
    end

    test "returns error with invalid certificate" do
      assert {:error, _} =
               Quire.Pades.Cms.build_signed_data(<<1::256>>, <<2::2048>>, <<1, 2, 3>>)
    end
  end

  describe "hash_byte_range/2" do
    test "computes SHA256 of concatenated byte ranges" do
      # Create a dummy PDF-like binary
      pdf = <<0::64, "hello", 0::64, "world", 0::64>>
      # Byte range: [0, 4] [68, 5] — but simple case
      hash = Quire.Pades.Cms.hash_byte_range(pdf, [0, byte_size(pdf)])
      expected = :crypto.hash(:sha256, pdf)
      assert hash == expected
    end

    test "hashes multiple byte ranges" do
      pdf = <<"AAAA", "BBBB", "CCCC">>
      # Hash the first and third ranges only
      hash = Quire.Pades.Cms.hash_byte_range(pdf, [0, 4, 8, 4])
      expected = :crypto.hash(:sha256, "AAAACCCC")
      assert hash == expected
    end
  end

  describe "DER encoding primitives" do
    test "encode_oid" do
      # SHA256 OID
      sha256_der = Quire.Pades.Cms.encode_oid({2, 16, 840, 1, 101, 3, 4, 2, 1})
      assert sha256_der == <<6, 9, 96, 134, 72, 1, 101, 3, 4, 2, 1>>

      # RSA encryption OID
      rsa_der = Quire.Pades.Cms.encode_oid({1, 2, 840, 113_549, 1, 1, 1})
      assert rsa_der == <<6, 9, 42, 134, 72, 134, 247, 13, 1, 1, 1>>

      # data OID
      data_der = Quire.Pades.Cms.encode_oid({1, 2, 840, 113_549, 1, 7, 1})
      assert data_der == <<6, 9, 42, 134, 72, 134, 247, 13, 1, 7, 1>>
    end

    test "encode_integer" do
      assert Quire.Pades.Cms.encode_integer(1) == <<2, 1, 1>>
      assert Quire.Pades.Cms.encode_integer(255) == <<2, 2, 0, 255>>
      assert Quire.Pades.Cms.encode_integer(0) == <<2, 1, 0>>
      assert Quire.Pades.Cms.encode_integer(256) == <<2, 2, 1, 0>>
    end

    test "encode_octet_string" do
      assert Quire.Pades.Cms.encode_octet_string(<<>>) == <<4, 0>>
      assert Quire.Pades.Cms.encode_octet_string(<<1, 2, 3>>) == <<4, 3, 1, 2, 3>>
    end

    test "encode_sequence" do
      seq =
        Quire.Pades.Cms.encode_sequence([
          Quire.Pades.Cms.encode_integer(1),
          Quire.Pades.Cms.encode_integer(2)
        ])

      assert seq == <<0x30, 6, 2, 1, 1, 2, 1, 2>>
    end

    test "encode_null" do
      assert Quire.Pades.Cms.encode_null() == <<5, 0>>
    end
  end

  # Helper to decode OID bytes
  defp decode_oid(<<first_byte, rest::binary>>) do
    first = div(first_byte, 40)
    second = rem(first_byte, 40)
    {components, _rest} = decode_base128_stream(rest, [])
    List.to_tuple([first, second | Enum.reverse(components)])
  end

  defp decode_base128_stream(<<>>, acc), do: {acc, <<>>}

  defp decode_base128_stream(bin, acc) do
    {value, rest} = decode_base128(bin, 0)
    decode_base128_stream(rest, [value | acc])
  end

  defp decode_base128(<<byte, rest::binary>>, acc) when byte < 0x80 do
    {acc * 128 + byte, rest}
  end

  defp decode_base128(<<byte, rest::binary>>, acc) do
    decode_base128(rest, acc * 128 + (byte - 128))
  end

  describe "ECDSA CMS signing" do
    setup do
      p12 = File.read!("test/support/fixtures/test_ecdsa_legacy.p12")
      {:ok, [ec_key], [ec_cert]} = Quire.Pades.Pkcs12.parse(p12, "testpass")
      %{ec_key_der: ec_key.key_der, ec_cert_der: ec_cert.der}
    end

    test "builds valid CMS with ECDSA signature", %{
      ec_key_der: ec_key_der,
      ec_cert_der: ec_cert_der
    } do
      content = "ecdsa test data"
      content_hash = :crypto.hash(:sha256, content)

      ecc_key = :public_key.der_decode(:PrivateKeyInfo, ec_key_der)
      signature = :public_key.sign(content_hash, :sha256, ecc_key)
      signature = :public_key.sign(content_hash, :sha256, ecc_key)

      assert {:ok, cms_der} =
               Quire.Pades.Cms.build_signed_data(content_hash, signature, ec_cert_der,
                 signature_algorithm: :ecdsa
               )

      assert byte_size(cms_der) < 2000

      {{0x30, outer_content}, _} = Quire.Pades.Cms.decode_tlv(cms_der)
      {{0x06, oid_bytes}, _rest2} = Quire.Pades.Cms.decode_tlv(outer_content)

      oid_tuple =
        oid_bytes
        |> then(fn <<first, rest::binary>> ->
          a = div(first, 40)
          b = rem(first, 40)
          {components, _} = decode_base128_stream(rest, [])
          List.to_tuple([a, b | Enum.reverse(components)])
        end)

      assert oid_tuple == {1, 2, 840, 113_549, 1, 7, 2}
    end
  end
end
