import Config

# Configure your database
config :quire, Quire.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "quire_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :quire, QuireWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "ZadAoaNfsY+o/PFmtE5rKVFJ/PqVhSEpcLU1YYNGK0pJTUNHRgCtZGEtt5e1IB36",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:quire, ~w(--sourcemap=inline --watch)]},
    esbuild_pdf: {Esbuild, :install_and_run, [:pdf_viewer, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:quire, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :quire, dev_routes: true

# Cloak vault for at-rest encryption — static dev key.
# **Never** use this key in production; configure via CLOAK_ENCRYPTION_KEY in
# config/runtime.exs.
config :quire, Quire.Vault,
  ciphers: [
    default:
      {Cloak.Ciphers.AES.GCM,
       tag: "AES.GCM.V1",
       key:
         <<178, 247, 240, 164, 221, 41, 4, 82, 100, 234, 45, 61, 183, 6, 123, 204, 182, 6, 96,
           211, 2, 9, 253, 253, 9, 91, 132, 190, 131, 0, 106, 145>>}
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# ── ChromicPDF on-demand mode (§3.6.6) ─────────────────────────────────────
#
# Instead of keeping a persistent headless Chrome alive for the whole app
# session (the library default), every print job spawns a temporary browser
# and is shut down the moment the job finishes — no Chrome process lingers
# between conversions.
#
# ConvertWorker.print_to_pdf_safely/2 gives each on-demand instance a
# unique per-job --user-data-dir profile and reaps exactly that process
# tree after the job (ChromicPDF's own teardown leaves the Chrome binary
# running on macOS until the whole VM exits). The GUI Chrome is never
# touched: it has no --headless/--remote-debugging-pipe and never carries
# a job profile marker.
#
# Trade-off: each conversion pays Chrome's startup cost (~1 s). Set to []
# to restore the persistent pool (prod default).
config :quire, chromic_pdf_opts: [on_demand: true]
